[project]
name = "committee-meeting"
version = "0.1.0"
description = "Committee Meeting Data Platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic",
    "sqlmodel",
]

[dependency-groups]
dev = [
    "pyrefly",
    "ruff",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [
    "src/committee_meeting/migrations/versions"
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "PL",  # pylint
    "I",   # isort
    "C90", # mccabe
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
project-excludes = [
    "src/committee_meeting/migrations/versions"
]
