[project]
name = "youtube-api"
version = "0.1.0"
description = "YouTube API Client for Congressional Tech"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
